name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows:
      - Build App
    types:
      - completed

jobs:
  deploy:
    permissions:
      contents: write
      deployments: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Create Deployment
      #   id: create_deployment
      #   run: |
      #     gh api -X POST "repos/${{ github.repository }}/deployments" \
      #       -F ref="${{ github.ref }}" \
      #       -F environment="production" \
      #       -F description="GitHub Pages Deployment" \
      #       -F auto_merge="false" \
      #       -F transient_environment="false" \
      #       -F production_environment="true" \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" > deployment.json
      #   env:
      #     GH_TOKEN: ${{ github.token }}

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          workflow_conclusion: success
          name: build
          path: dist

      - name: Deploy to GitHub Pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d dist -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Update Deployment Status
      #   run: |
      #     deployment_id=$(cat deployment.json | jq -r '.id')
      #     gh api -X POST "repos/${{ github.repository }}/deployments/${deployment_id}/statuses" \
      #       -F state="success" \
      #       -F environment_url="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}" \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
      #   env:
      #     GH_TOKEN: ${{ github.token }}
